# Generated by Django 2.0 on 2020-08-05 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPersona',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('cuit', models.CharField(max_length=11, verbose_name='Cuit (*)')),
                ('dni', models.CharField(max_length=10, verbose_name='DNI (*)')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre (*)')),
                ('apellido', models.CharField(max_length=50, null=True, verbose_name='Apellido (*)')),
                ('domicilio', models.CharField(max_length=50, null=True, verbose_name='Domicilio (*)')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='e-mail')),
                ('telefono', models.IntegerField(default=False, verbose_name='Telefono')),
                ('fecha_nac', models.DateTimeField(verbose_name='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical persona',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuit', models.CharField(max_length=11, verbose_name='Cuit (*)')),
                ('dni', models.CharField(max_length=10, verbose_name='DNI (*)')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre (*)')),
                ('apellido', models.CharField(max_length=50, null=True, verbose_name='Apellido (*)')),
                ('domicilio', models.CharField(max_length=50, null=True, verbose_name='Domicilio (*)')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='e-mail')),
                ('telefono', models.IntegerField(default=False, verbose_name='Telefono')),
                ('fecha_nac', models.DateTimeField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=10, verbose_name='Sexo (*)')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.Sexo'),
        ),
        migrations.AddField(
            model_name='historicalpersona',
            name='sexo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personas.Sexo'),
        ),
    ]
