# Generated by Django 2.0 on 2020-08-05 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_d', models.DateField()),
                ('fecha_h', models.DateField()),
                ('nro_dis', models.CharField(max_length=8, verbose_name='N Disponibilidad ')),
                ('resumen', models.CharField(max_length=250, verbose_name='Resumen ')),
                ('nombre_archivo', models.CharField(max_length=50, verbose_name='Nombre de Archivo ')),
                ('fecha_c', models.DateField()),
                ('anexo', models.CharField(max_length=250, verbose_name='Anexo ')),
                ('contrato', models.CharField(max_length=10, verbose_name='Contrato ')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=256, verbose_name='Estado ')),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=256, verbose_name='Objeto ')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('solicitante', models.CharField(max_length=256, verbose_name='Solicitante ')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contrato.Estado'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='objeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contrato.Objeto'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.Persona'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contrato.Solicitante'),
        ),
    ]
